name: Deploy PROD
on:
  push:
    branches: [ main ]

jobs:
  functions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dirs.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '5'
      - name: Get directories
        id: dirs
        run: |
          function join_by { local d=${1-} f=${2-}; if shift 2; then printf %s "$f" "${@/#/$d}"; fi; }

          # Excluding all "hidden" directories by: sed 's/^\..*$//g'
          CHANGES=($(git diff HEAD~ --dirstat=files,0 |sed 's/^ *[0-9.]*% *//g'|sed 's/^\..*$//g'|sed 's/\/$//g'|sort -u))
          if [[ ${#CHANGES[@]} -gt 0 ]]
          then
              DIRS='["'$(join_by '","' ${CHANGES[@]})'"]'
          else
              DIRS='[]'
          fi

          MATRIX_JSON='{"function":'${DIRS}'}'

          echo "MATRIX_JSON: ${MATRIX_JSON}"
          echo "::set-output name=matrix::${MATRIX_JSON}"
  deployment:
    needs: [functions]
    if: ${{ ! contains(needs.functions.outputs.matrix, '"function":[]') }}
    strategy:
      matrix: ${{fromJson(needs.functions.outputs.matrix)}}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
      - name: Build
        working-directory: ${{ matrix.function }}
        run: |
          GOOS=linux go build main.go
          zip ${{ matrix.function }}.zip main
          openssl dgst -sha256 -binary ${{ matrix.function }}.zip | openssl enc -base64 > ${{ matrix.function }}.zip.sha256
      - name: upload code
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_PROD }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_PROD }}
          aws-region: "us-east-2"
          aws-bucket: "testigoelectoral-artifacts-prod"
          destination-dir: "/lambda/${{ matrix.function }}/"
          bucket-root: "/"
          public: false
          file-path: "${{ matrix.function }}/${{ matrix.function }}.zip"
      - name: upload sha
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_PROD }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_PROD }}
          aws-region: "us-east-2"
          aws-bucket: "testigoelectoral-artifacts-prod"
          destination-dir: "/lambda/${{ matrix.function }}/"
          bucket-root: "/"
          public: false
          file-path: "${{ matrix.function }}/${{ matrix.function }}.zip.sha256"
